/**
 * Hand-written TypeScript types mirroring supabase/migrations/0001_init.sql.
 *
 * These are written by hand rather than generated by the Supabase CLI, because
 * Phase 1 has no database connection and nothing to generate from. When the
 * migration is eventually applied, `supabase gen types typescript` becomes the
 * source of truth and this file is replaced -- until then it is the contract,
 * and it must be edited in the same commit as any change to the SQL.
 *
 * Conventions:
 *   - Postgres `uuid`        -> string
 *   - Postgres `timestamptz` -> string (ISO 8601, as PostgREST returns it)
 *   - Postgres `numeric`     -> number  (see note on precision below)
 *   - Nullable columns       -> `| null`, never `?`. A column that exists and
 *                               is NULL is different from a key that is absent,
 *                               and collapsing the two hides real bugs.
 *   - Columns with a DB default are optional on Insert, required on Row.
 *   - Row and Insert shapes are declared with `type`, never `interface`.
 *
 * THAT LAST ONE IS LOAD-BEARING. postgrest-js requires every Row and Insert to
 * satisfy `Record<string, unknown>`. TypeScript gives object *type aliases* an
 * implicit index signature and deliberately does not give one to *interfaces*,
 * because an interface can be reopened by declaration merging and so its key
 * set is never final. An interface here therefore fails the library's
 * structural check -- and the failure is silent: the schema falls back to
 * `never`, and every query result in the app becomes `never` with the error
 * reported at the call site ("Property 'id' does not exist on type 'never'"),
 * nowhere near this file. Do not convert these back to interfaces.
 *
 * NOTE ON `numeric`: Postgres numeric is arbitrary-precision; JS number is a
 * double. Every numeric column here (kd_ratio, avg_damage, rates) is a small
 * magnitude with at most 3 decimal places, so the double representation is
 * exact enough. Do not add a high-precision numeric column without revisiting
 * this -- it would need to be typed as string.
 */

// ---------------------------------------------------------------------------
// Enums -- mirror of SECTION 1 of 0001_init.sql
// ---------------------------------------------------------------------------

/** BGMI squad roles. `flex` is a competence, not "unassigned" -- absence is null. */
export type PlayerRole =
  | 'igl'
  | 'assaulter'
  | 'sniper'
  | 'support'
  | 'flex';

/** Lifecycle of one matchmaking_queue row. */
export type QueueState =
  | 'waiting'
  | 'matching'
  | 'matched'
  | 'cancelled'
  | 'expired';

/** Lifecycle of one match. */
export type MatchStatus =
  | 'forming'
  | 'ready'
  | 'in_progress'
  | 'completed'
  | 'abandoned';

/** Communication requirement. Applied as a hard filter, not a weight. */
export type CommPreference =
  | 'voice_required'
  | 'voice_optional'
  | 'text_only'
  | 'silent';

/**
 * Which scorer produced `matches.synergy_score`.
 * Modelled as text + CHECK in SQL rather than an enum -- see the fallback path
 * in docs/architecture.md section 4.
 */
export type ScoringSource = 'ml' | 'rule_based';

/** Runtime-usable lists, for validation and for populating select inputs. */
export const PLAYER_ROLES: readonly PlayerRole[] = [
  'igl',
  'assaulter',
  'sniper',
  'support',
  'flex',
] as const;

export const QUEUE_STATES: readonly QueueState[] = [
  'waiting',
  'matching',
  'matched',
  'cancelled',
  'expired',
] as const;

export const MATCH_STATUSES: readonly MatchStatus[] = [
  'forming',
  'ready',
  'in_progress',
  'completed',
  'abandoned',
] as const;

export const COMM_PREFERENCES: readonly CommPreference[] = [
  'voice_required',
  'voice_optional',
  'text_only',
  'silent',
] as const;

// ---------------------------------------------------------------------------
// Shared aliases
//
// These carry no extra type safety on their own -- they are documentation at
// the point of use, so a reader of a function signature can tell a uuid from a
// display name without opening this file.
// ---------------------------------------------------------------------------

/** UUID v4, as produced by gen_random_uuid(). */
export type UUID = string;

/** ISO 8601 timestamp with timezone. */
export type Timestamptz = string;

/**
 * A 0-100 normalized score. CHECK-constrained in Postgres; TypeScript cannot
 * express the range, so the alias exists to make the intent visible and to give
 * validators in lib/ a single name to key on.
 */
export type Score0To100 = number;

// ---------------------------------------------------------------------------
// profiles
// ---------------------------------------------------------------------------

export type Profile = {
  id: UUID;
  /**
   * null     = synthetic seed profile (ML training data, no human behind it)
   * non-null = real authenticated user
   * UNIQUE in the database: at most one profile per auth account.
   */
  auth_user_id: UUID | null;
  display_name: string;
  /** In-game name. UNIQUE -- the key used to reconcile external match records. */
  bgmi_ign: string;
  region: string | null;
  avatar_url: string | null;
  bio: string | null;
  is_active: boolean;
  /** Synthetic row written by scripts/seed.ts (0005). */
  is_seed: boolean;
  /** May form squads and reset demo tournaments (0006). Service-role writes only. */
  is_organiser: boolean;
  created_at: Timestamptz;
  updated_at: Timestamptz;
}

export type ProfileInsert = {
  id?: UUID;
  auth_user_id?: UUID | null;
  display_name: string;
  bgmi_ign: string;
  region?: string | null;
  avatar_url?: string | null;
  bio?: string | null;
  is_active?: boolean;
  is_seed?: boolean;
  is_organiser?: boolean;
  created_at?: Timestamptz;
  updated_at?: Timestamptz;
}

export type ProfileUpdate = Partial<ProfileInsert>;

// ---------------------------------------------------------------------------
// player_stats -- 1:1 with profiles. Written by the ML service.
// ---------------------------------------------------------------------------

export type PlayerStats = {
  id: UUID;
  profile_id: UUID;

  // Raw performance figures.
  kd_ratio: number;
  avg_damage: number;
  /** Seconds. */
  avg_survival_time: number;
  /** Percent, 0-100. */
  headshot_rate: number;
  /** Percent, 0-100. */
  win_rate: number;

  // Normalized skill axes. Every one is CHECK-constrained 0-100 in Postgres.
  aim_score: Score0To100;
  game_sense: Score0To100;
  teamwork_score: Score0To100;
  clutch_score: Score0To100;
  consistency_score: Score0To100;
  /** Composite of the five axes. Stored, not computed -- the weighting is owned
   *  by the ML service and changes between model versions. */
  overall_rating: Score0To100;

  matches_played: number;
  matches_won: number;

  /** null = never scored. Distinct from "scored and landed on the defaults". */
  last_computed_at: Timestamptz | null;

  /** Synthetic row written by scripts/seed.ts (0005). */
  is_seed: boolean;
  created_at: Timestamptz;
  updated_at: Timestamptz;
}

export type PlayerStatsInsert = {
  id?: UUID;
  profile_id: UUID;
  kd_ratio?: number;
  avg_damage?: number;
  avg_survival_time?: number;
  headshot_rate?: number;
  win_rate?: number;
  aim_score?: Score0To100;
  game_sense?: Score0To100;
  teamwork_score?: Score0To100;
  clutch_score?: Score0To100;
  consistency_score?: Score0To100;
  overall_rating?: Score0To100;
  matches_played?: number;
  matches_won?: number;
  last_computed_at?: Timestamptz | null;
  is_seed?: boolean;
  created_at?: Timestamptz;
  updated_at?: Timestamptz;
}

export type PlayerStatsUpdate = Partial<Omit<PlayerStatsInsert, 'profile_id'>>;

// ---------------------------------------------------------------------------
// player_preferences -- 1:1 with profiles. Written by the user, never by ML.
// ---------------------------------------------------------------------------

export type PlayerPreferences = {
  id: UUID;
  profile_id: UUID;
  primary_role: PlayerRole;
  /** null means "no second role" -- which is not the same as 'flex'. */
  secondary_role: PlayerRole | null;
  comm_preference: CommPreference;
  /** Accepted teammate skill band, same 0-100 scale as overall_rating. */
  min_teammate_skill: Score0To100;
  max_teammate_skill: Score0To100;
  wants_ranked: boolean;
  languages: string[];
  /** null = no ping constraint stated. */
  max_ping_ms: number | null;
  /** Synthetic row written by scripts/seed.ts (0005). */
  is_seed: boolean;
  created_at: Timestamptz;
  updated_at: Timestamptz;
}

export type PlayerPreferencesInsert = {
  id?: UUID;
  profile_id: UUID;
  primary_role?: PlayerRole;
  secondary_role?: PlayerRole | null;
  comm_preference?: CommPreference;
  min_teammate_skill?: Score0To100;
  max_teammate_skill?: Score0To100;
  wants_ranked?: boolean;
  languages?: string[];
  max_ping_ms?: number | null;
  is_seed?: boolean;
  created_at?: Timestamptz;
  updated_at?: Timestamptz;
}

export type PlayerPreferencesUpdate = Partial<
  Omit<PlayerPreferencesInsert, 'profile_id'>
>;

// ---------------------------------------------------------------------------
// player_availability -- 1:N per profile.
// ---------------------------------------------------------------------------

/** 0 = Sunday ... 6 = Saturday. Matches both JS getDay() and Postgres dow. */
export type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type PlayerAvailability = {
  id: UUID;
  profile_id: UUID;
  day_of_week: DayOfWeek;
  /** Minutes from local midnight, 0-1440. start < end is enforced in the DB. */
  start_minute: number;
  end_minute: number;
  /** -720 (UTC-12) to +840 (UTC+14). */
  timezone_offset_minutes: number;
  /** Synthetic row written by scripts/seed.ts (0005). */
  is_seed: boolean;
  created_at: Timestamptz;
  updated_at: Timestamptz;
}

export type PlayerAvailabilityInsert = {
  id?: UUID;
  profile_id: UUID;
  day_of_week: DayOfWeek;
  start_minute: number;
  end_minute: number;
  timezone_offset_minutes?: number;
  is_seed?: boolean;
  created_at?: Timestamptz;
  updated_at?: Timestamptz;
}

export type PlayerAvailabilityUpdate = Partial<
  Omit<PlayerAvailabilityInsert, 'profile_id'>
>;

// ---------------------------------------------------------------------------
// matchmaking_queue
// ---------------------------------------------------------------------------

export type MatchmakingQueueEntry = {
  id: UUID;
  /** UNIQUE -- a player is in the pool at most once. */
  profile_id: UUID;
  state: QueueState;
  /** null = no role preference for this queue entry. */
  desired_role: PlayerRole | null;
  /** Snapshot of the preference band taken at enqueue time, deliberately not a
   *  join: the matcher must see a stable band even if preferences are edited. */
  min_skill: Score0To100;
  max_skill: Score0To100;
  party_size: number;
  target_squad_size: number;
  region: string | null;
  enqueued_at: Timestamptz;
  /** null = no expiry set. */
  expires_at: Timestamptz | null;
  /**
   * Non-null if and only if `state === 'matched'`. Enforced by a CHECK in
   * Postgres; the discriminated union below makes the same guarantee usable by
   * the type checker.
   */
  matched_match_id: UUID | null;
  created_at: Timestamptz;
  updated_at: Timestamptz;
}

/**
 * Type-level mirror of the `matchmaking_queue_matched_requires_match` CHECK.
 * Narrowing on `state` gives you `matched_match_id` without a null assertion.
 */
export type MatchmakingQueueEntryChecked =
  | (Omit<MatchmakingQueueEntry, 'state' | 'matched_match_id'> & {
      state: 'matched';
      matched_match_id: UUID;
    })
  | (Omit<MatchmakingQueueEntry, 'state' | 'matched_match_id'> & {
      state: Exclude<QueueState, 'matched'>;
      matched_match_id: null;
    });

export type MatchmakingQueueInsert = {
  id?: UUID;
  profile_id: UUID;
  state?: QueueState;
  desired_role?: PlayerRole | null;
  min_skill?: Score0To100;
  max_skill?: Score0To100;
  party_size?: number;
  target_squad_size?: number;
  region?: string | null;
  enqueued_at?: Timestamptz;
  expires_at?: Timestamptz | null;
  matched_match_id?: UUID | null;
  created_at?: Timestamptz;
  updated_at?: Timestamptz;
}

export type MatchmakingQueueUpdate = Partial<
  Omit<MatchmakingQueueInsert, 'profile_id'>
>;

// ---------------------------------------------------------------------------
// matches
// ---------------------------------------------------------------------------

export type Match = {
  id: UUID;
  status: MatchStatus;
  map_name: string | null;
  mode: string | null;
  is_ranked: boolean;
  squad_size: number;
  /** null until a scorer has run. */
  synergy_score: Score0To100 | null;
  /** Provenance for the ML-unavailable fallback. See architecture.md section 4. */
  scoring_source: ScoringSource;
  /** Set when the match was formed for a tournament (0005). */
  tournament_id: UUID | null;
  /** Per-component scores behind synergy_score, as produced at formation. */
  squad_score_components: SquadScoreComponents | null;
  /** "Why this squad" lines, stored as produced at formation time. */
  reasons: string[] | null;
  /** Synthetic row written by scripts/seed.ts (0005). */
  is_seed: boolean;
  created_at: Timestamptz;
  started_at: Timestamptz | null;
  ended_at: Timestamptz | null;
  updated_at: Timestamptz;
}

export type MatchInsert = {
  id?: UUID;
  status?: MatchStatus;
  map_name?: string | null;
  mode?: string | null;
  is_ranked?: boolean;
  squad_size?: number;
  synergy_score?: Score0To100 | null;
  scoring_source?: ScoringSource;
  tournament_id?: UUID | null;
  squad_score_components?: SquadScoreComponents | null;
  reasons?: string[] | null;
  is_seed?: boolean;
  created_at?: Timestamptz;
  started_at?: Timestamptz | null;
  ended_at?: Timestamptz | null;
  updated_at?: Timestamptz;
}

export type MatchUpdate = Partial<MatchInsert>;

// ---------------------------------------------------------------------------
// match_participants
// ---------------------------------------------------------------------------

export type MatchParticipant = {
  id: UUID;
  match_id: UUID;
  profile_id: UUID;
  /**
   * The role given in THIS match, which routinely differs from the player's
   * preferred role. The divergence is a training signal -- do not resolve it by
   * reading player_preferences instead.
   */
  assigned_role: PlayerRole | null;
  is_leader: boolean;
  joined_at: Timestamptz;
  /** null = present at the end of the match. */
  left_at: Timestamptz | null;
  /** Synthetic row written by scripts/seed.ts (0005). */
  is_seed: boolean;
  created_at: Timestamptz;
  updated_at: Timestamptz;
}

export type MatchParticipantInsert = {
  id?: UUID;
  match_id: UUID;
  profile_id: UUID;
  assigned_role?: PlayerRole | null;
  is_leader?: boolean;
  joined_at?: Timestamptz;
  left_at?: Timestamptz | null;
  is_seed?: boolean;
  created_at?: Timestamptz;
  updated_at?: Timestamptz;
}

export type MatchParticipantUpdate = Partial<
  Omit<MatchParticipantInsert, 'match_id' | 'profile_id'>
>;

// ---------------------------------------------------------------------------
// match_feedback -- the supervised label.
// ---------------------------------------------------------------------------

/** 1-5, CHECK-constrained. 0 is excluded: "not rated" is an absent row. */
export type FeedbackRating = 1 | 2 | 3 | 4 | 5;

export type MatchFeedback = {
  id: UUID;
  match_id: UUID;
  rater_profile_id: UUID;
  ratee_profile_id: UUID;
  rating: FeedbackRating;
  /** Optional 0-100 axis, directly comparable to player_stats.teamwork_score. */
  teamwork_rating: Score0To100 | null;
  would_play_again: boolean | null;
  comment: string | null;
  /** Synthetic row written by scripts/seed.ts (0005). */
  is_seed: boolean;
  created_at: Timestamptz;
  updated_at: Timestamptz;
}

export type MatchFeedbackInsert = {
  id?: UUID;
  match_id: UUID;
  rater_profile_id: UUID;
  ratee_profile_id: UUID;
  rating: FeedbackRating;
  teamwork_rating?: Score0To100 | null;
  would_play_again?: boolean | null;
  comment?: string | null;
  is_seed?: boolean;
  created_at?: Timestamptz;
  updated_at?: Timestamptz;
}

export type MatchFeedbackUpdate = Partial<
  Omit<
    MatchFeedbackInsert,
    'match_id' | 'rater_profile_id' | 'ratee_profile_id'
  >
>;


// ---------------------------------------------------------------------------
// 0005: tournaments, registrations, model versions, read surfaces.
// ---------------------------------------------------------------------------

export type TournamentStatus = 'draft' | 'open' | 'matched' | 'completed';

export const TOURNAMENT_STATUSES: readonly TournamentStatus[] = [
  'draft',
  'open',
  'matched',
  'completed',
] as const;

/** Per-component scores stored on matches.squad_score_components. */
export type SquadScoreComponents = Record<string, number>;

export type Tournament = {
  id: UUID;
  name: string;
  slug: string;
  description: string | null;
  squad_size: number;
  region: string | null;
  starts_at: Timestamptz;
  registration_closes_at: Timestamptz | null;
  status: TournamentStatus;
  /** Last formation result; shape owned by lib/scoring/formation.ts. */
  formation_summary: Json | null;
  formed_at: Timestamptz | null;
  is_seed: boolean;
  created_at: Timestamptz;
  updated_at: Timestamptz;
};

export type TournamentInsert = {
  id?: UUID;
  name: string;
  slug: string;
  description?: string | null;
  squad_size?: number;
  region?: string | null;
  starts_at: Timestamptz;
  registration_closes_at?: Timestamptz | null;
  status?: TournamentStatus;
  formation_summary?: Json | null;
  formed_at?: Timestamptz | null;
  is_seed?: boolean;
  created_at?: Timestamptz;
  updated_at?: Timestamptz;
};

export type TournamentUpdate = Partial<TournamentInsert>;

export type TournamentRegistration = {
  id: UUID;
  tournament_id: UUID;
  profile_id: UUID;
  desired_role: PlayerRole | null;
  registered_at: Timestamptz;
  is_seed: boolean;
};

export type TournamentRegistrationInsert = {
  id?: UUID;
  tournament_id: UUID;
  profile_id: UUID;
  desired_role?: PlayerRole | null;
  registered_at?: Timestamptz;
  is_seed?: boolean;
};

export type ModelVersion = {
  id: UUID;
  version: string;
  algorithm: string;
  trained_at: Timestamptz;
  n_train: number | null;
  n_test: number | null;
  metrics: Json | null;
  baselines: Json | null;
  feature_importance: Json | null;
  is_active: boolean;
  created_at: Timestamptz;
};

export type ModelVersionInsert = {
  id?: UUID;
  version: string;
  algorithm: string;
  trained_at?: Timestamptz;
  n_train?: number | null;
  n_test?: number | null;
  metrics?: Json | null;
  baselines?: Json | null;
  feature_importance?: Json | null;
  is_active?: boolean;
  created_at?: Timestamptz;
};

/** leaderboard_v: the only public window onto player_preferences.primary_role. */
export type LeaderboardRow = {
  profile_id: UUID;
  display_name: string;
  bgmi_ign: string;
  region: string | null;
  primary_role: PlayerRole | null;
  overall_rating: number | null;
  kd_ratio: number | null;
  win_rate: number | null;
  matches_played: number | null;
};

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ---------------------------------------------------------------------------
// Aggregate schema type
//
// Shaped to match what `supabase gen types typescript` emits, so that swapping
// this file for a generated one in Phase 2 does not require touching call
// sites: createClient<Database>(...) keeps working unchanged.
// ---------------------------------------------------------------------------

/**
 * `Relationships: []` on every table is required, not decorative.
 *
 * postgrest-js checks the schema against its own `GenericTable`, which declares
 * `Relationships: GenericRelationship[]`. Omitting the key does not produce an
 * error at the type definition -- it makes the schema fail that structural
 * check, and every query result silently degrades to `never`. The symptom is
 * `Property 'id' does not exist on type 'never'` at the call site, a long way
 * from the cause.
 *
 * Empty arrays are honest here: the arrays describe embedded-resource joins
 * (`select('*, player_stats(*)')`), and Phase 2 issues none. Generated types
 * will populate them from the real foreign keys when this file is replaced.
 */
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: Profile;
        Insert: ProfileInsert;
        Update: ProfileUpdate;
        Relationships: [];
      };
      player_stats: {
        Row: PlayerStats;
        Insert: PlayerStatsInsert;
        Update: PlayerStatsUpdate;
        Relationships: [];
      };
      player_preferences: {
        Row: PlayerPreferences;
        Insert: PlayerPreferencesInsert;
        Update: PlayerPreferencesUpdate;
        Relationships: [];
      };
      player_availability: {
        Row: PlayerAvailability;
        Insert: PlayerAvailabilityInsert;
        Update: PlayerAvailabilityUpdate;
        Relationships: [];
      };
      matchmaking_queue: {
        Row: MatchmakingQueueEntry;
        Insert: MatchmakingQueueInsert;
        Update: MatchmakingQueueUpdate;
        Relationships: [];
      };
      matches: {
        Row: Match;
        Insert: MatchInsert;
        Update: MatchUpdate;
        Relationships: [];
      };
      match_participants: {
        Row: MatchParticipant;
        Insert: MatchParticipantInsert;
        Update: MatchParticipantUpdate;
        Relationships: [];
      };
      match_feedback: {
        Row: MatchFeedback;
        Insert: MatchFeedbackInsert;
        Update: MatchFeedbackUpdate;
        Relationships: [];
      };
      tournaments: {
        Row: Tournament;
        Insert: TournamentInsert;
        Update: TournamentUpdate;
        Relationships: [];
      };
      tournament_registrations: {
        Row: TournamentRegistration;
        Insert: TournamentRegistrationInsert;
        Update: Partial<TournamentRegistrationInsert>;
        Relationships: [];
      };
      model_versions: {
        Row: ModelVersion;
        Insert: ModelVersionInsert;
        Update: Partial<ModelVersionInsert>;
        Relationships: [];
      };
    };
    Views: {
      leaderboard_v: {
        Row: LeaderboardRow;
        Relationships: [];
      };
    };
    Functions: {
      public_stats: {
        Args: Record<string, never>;
        Returns: { players: number; tournaments: number; squads_formed: number }[];
      };
      analytics_overview: {
        Args: Record<string, never>;
        Returns: Json;
      };
    };
    Enums: {
      player_role: PlayerRole;
      queue_state: QueueState;
      match_status: MatchStatus;
      comm_preference: CommPreference;
      tournament_status: TournamentStatus;
    };
  };
}

/** Convenience accessors, so call sites read as `Tables<'profiles'>`. */
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

// ---------------------------------------------------------------------------
// Composite shapes
//
// Not tables. These are the joined views the recommender and the UI actually
// operate on, named here so the shape of a scorer's input is a declared
// contract rather than an ad-hoc object literal.
// ---------------------------------------------------------------------------

/** A player with everything the scorer needs, in one object. */
export interface PlayerVector {
  profile: Profile;
  stats: PlayerStats | null;
  preferences: PlayerPreferences | null;
  availability: PlayerAvailability[];
}

/** One seat in a proposed squad. */
export interface RoleAssignment {
  profile_id: UUID;
  assigned_role: PlayerRole;
}

/**
 * The return shape shared by BOTH scorers. The ML client and the rule-based
 * fallback in lib/ implement this identically -- which is what allows the
 * caller in app/ to swap between them without a branch in its own logic.
 */
export interface SquadScore {
  synergy_score: Score0To100;
  assignments: RoleAssignment[];
  scoring_source: ScoringSource;
}
